spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.99.205.195:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false

server:
  port:  8024

eureka:
  client:
    service-url:
      defaultZone : http://47.99.205.195:8761/eureka/
  instance:
    hostname: localhost
env:
  test
